(defun print-result (players points looser)
   (format t "~%~a~%" "-------------------------------------------------------------------------")
   (format t "~a~%" "spele ir beigusies. speletajiem tika pieskaitits sekojoss soda punktu      ")
   (format t "~a~%" "skaits:")

   ;; (format t " ~{~a~#[~:;~% ~]~}" players)
   (display-list 1 players points)
   
   (cond ((equal (length looser) 1)
          (format t "~%~%~a~%" "=========================================================================")     
          (format t "                        speli ir zaudejis ~@(~a.~)~%" (car looser)                   ) 
          (format t "~a~%" "========================================================================="))
         (t(equal (length looser) 2) 
            (format t "~%~%~a~%" "=========================================================================")     
            (format t "                    speli ir zaudejis ~@(~a~) ~(~a.~)~%" (car looser) (cadr looser)  ) 
            (format t "~a~%" "========================================================================="))))

(defun display-list (i lst l)
    (cond ((null lst) nil)
          (t (cond 
              ((equal (length (car lst)) 1) 
                  (format t "~& ~{~2d) ~@(~2@a:~) ~(~1@a~)~}" (list i (caar lst) (caar l))) 
                  (displaylist (+ i 1) (cdr lst) (cdr l)))
              ((equal (length (car lst)) 2)
                  (format t "~& ~{~2d) ~@(~2@a~) ~(~1@a:~) ~(~1@a~)~}" (list i (caar lst) (cadar lst) (caar l)))
                  (display-list (+ i 1) (cdr lst) (cdr l)))))))

(defun print-cards (player cards)
  (format t "~%~@(~a~):~%" player)
  (display-card (redraw cards) 1)
  (format t "~%"))

(defun redraw(lst)
  (cond ((null lst) nil)
        (t(apend (get-nominal (caar lst)) (redraw (cdr lst))))))

(defun get-nominal (nm)
  (cond 
    ((equal nm 7) 'septinieks)
    ((equal nm 8) 'astotnieks)
    ((equal nm 9) 'devitnieks)
    ((equal nm 10) 'desmitnieks)
    ((equal nm 11) 'kalps)
    ((equal nm 12) 'damma)
    ((equal nm 13) 'kungs)
    ((equal nm 14) 'duzis)))

(defun get-mast (mst)
  (cond 
    ((equal mst 1) 'sirds)
    ((equal mst 2) 'bubi)
    ((equal mst 3) 'kristi)
    ((equal mst 4) 'piki)))

(defun display-card (lst i)
  (cond ((null lst) nil)
        (t(format t "~& ~{~2d) ~(~2@a~) ~(~1@a~)~}" (list i (caar lst) (cadar lst)))
        (display-card (cdr lst) (+ i 1)))))

(defun print-rules(num)
  (cond 
    ((equal num 0)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                           speles noteikumi:                             ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "   spele \"king\". speletaju kartiba cilveks - dators - cilveks - dators.")
      (format t "~a~%" "spele tiek izmantotas 32 kartis (karsu komplekta neietilpst sesinieki).  ")
      (format t "~a~%" "spele sastav no 6 apaksspelem, kas sakas, kad kartis tiek izdalitas un   ") 
      (format t "~a~%" "beidzas, kad visas tiek izmestas ara.")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "   pirmais, kas sak apaksspeli izmet ara vienu karts, parejiem ir jaizmet")
      (format t "~a~%" "ara tada pasa masts karts, ja tada masts nav, ir jaizmet ara jebkura cita")
      (format t "~a~%" "masts karts. speletajs, kurs izmeta ara vajadzigas masts karti ar")
      (format t "~a~%" "vislielako nominalu, nem ta saucamo stiki. tam, kurs panema stiki, tiek")
      (format t "~a~%~%" "pieskaititi soda punkti atkariba no apaksspeles noteikumiem."))
    ((equal num 1)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                           pirma apaksspele:                             ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "  nedrikst nemt nevienu no stikiem. par katru panemto stiki 2 soda punkti")
      (format t "~a~%~%" "(-2). maksimalais soda punktu skaits: -16."))
    ((equal num 2)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                           otra apaksspele:                              ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "  nedrikst nemt nevienu sirds karti. par katru panemto sirds karti 2 soda") 
      (format t "~a~%" "punkti (-2). nedrikst sakt speli ar sirds kartim, ja rokas ir citas masts")
      (format t "~a~%~%" "kartis. maksimalais soda punktu skaits: -16."))
    ((equal num 3)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                            tresa apaksspele:                            ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "  nedrikst nemt nevienu kalpu. par katru panemto kalpu 4 soda punkti(-4).") 
      (format t "~a~%~%" "maksimalais soda punktu skaits: -16."))
    ((equal num 4)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                           ceturta appakspele:                           ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "   nedrikst nemt nevienu damu. par katru panemto damu 4 soda punkti (-4).") 
      (format t "~a~%~%" "maksimalais soda punktu skaits: -16."))
    ((equal num 5)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                           piekta appakspele:                            ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "   nedrikst nemt 2 pedejus stikus. par katru panemto stiki 8 soda punkti ") 
      (format t "~a~%~%" "(-8). maksimalais soda punktu skaits: -16."))
    ((equal num 6)
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "                            sesta appakspele:                            ")
      (format t "~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "  nedrikst nemt sirds karali. ja uz rokam nav vajadzigas masts karts un  ")
      (format t "~a~%" "ir sirds karalis, tad obligati ir jaiet ar to. par sirds karali 16 soda  ")
      (format t "~a~%" "punkti (-16). nedrikst sakt speli ar sirds kartim, ja uz rokam ir citu   ")
      (format t "~a~%~%" "mastu kartis."))))

(defun print-error (num)
  (cond 
    ((= num 0)
      (format nil "~a" "spele var spelet tikai 4 speletaji!"))
    ((= num 1)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "kluda! jums nav pieejama tada karts. ievadiet karts numuru, ar kuru jus"    ) 
      (format t "~a~%" "gribat izdarit gajienu."                                                    )
      (format t "~a~%" "-------------------------------------------------------------------------" ))
    ((= num 2)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "kluda! jus nevarat izmest so karti, jums uz rokam ir bubi. ievadiet karts"  ) 
      (format t "~a~%" "numuru, ar kuru jus gribat izdarit gajienu."                                )
      (format t "~a~%" "-------------------------------------------------------------------------" ))
    ((= num 3)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "kluda! jus nevarat izmest so karti, jums uz rokam ir krusti. ievadiet      ") 
      (format t "~a~%" "karts numuru, ar kuru jus gribat izdarit gajienu."                          )
      (format t "~a~%" "-------------------------------------------------------------------------" ))
    ((= num 4)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "kluda! jus nevarat izmest so karti, jums uz rokam ir piki. ievadiet karts"  ) 
      (format t "~a~%" "numuru, ar kuru jus gribat izdarit gajienu."                                )
      (format t "~a~%" "-------------------------------------------------------------------------" ))
    ((= num 5)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "kluda! jus nevarat izmest so karti, jums uz rokam ir sirdis. ievadiet      ") 
      (format t "~a~%" "karts numuru, ar kuru jus gribat izdarit gajienu."                          )
      (format t "~a~%" "-------------------------------------------------------------------------" ))
    ((= num 6)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "kluda! jus nedrikstat sakt speli ar sirds masts karti, jo jums uz rokam    ") 
      (format t "~a~%" "ir citu masts kartis. ievadiet karts numuru, ar kuru jus saksiet speli."    )
      (format t "~a~%" "-------------------------------------------------------------------------" ))
    ((= num 7)
      (format t "~%~a~%" "-------------------------------------------------------------------------")
      (format t "~a~%" "jus nedriksat izdarit sadu gajienu! jums uz rokam ir sirds karalis, ar     ") 
      (format t "~a~%" "kuru jums obligati ir jastaiga."                                            )
      (format t "~a~%" "-------------------------------------------------------------------------" ))))

#|--------------------------------------------------------------------------------------------------|#

;(defun printmessage(player points)
;)

;; printcards 'anna '((7 4) (8 4) (9 4) (10 4) (11 4) (12 4) (13 4) (14 4) (7 2) (8 2) (9 2) (10 2) (11 2) (12 2) (13 2) (14 2))

;; printresult '((anna) (pirmais dators) (vasilijs) (otrais dators)) '((-16) (-16) (-12) (-20)) '(otrais dators)
