//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HealthCentreModel", "FK_Ārstēšana_Slimība", "Slimība", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HealthSystem.Business.Slimība), "Ārstēšana", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HealthSystem.Business.Ārstēšana))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HealthCentreModel", "FK_Ārstēšana_ĀrstsPersona", "ĀrstsPacients", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HealthSystem.Business.ĀrstsPacients), "Ārstēšana", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HealthSystem.Business.Ārstēšana))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HealthCentreModel", "ĀrstsĀrstsPacients", "Ārsts", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HealthSystem.Business.Ārsts), "ĀrstsPacients", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HealthSystem.Business.ĀrstsPacients))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HealthCentreModel", "PacientsĀrstsPacients", "Pacients", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HealthSystem.Business.Pacients), "ĀrstsPacients", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HealthSystem.Business.ĀrstsPacients))]

// Original file name:
// Generation date: 09.06.2011 22:36:26
namespace HealthSystem.Business
{
    
    /// <summary>
    /// There are no comments for MapConnection in the schema.
    /// </summary>
    public partial class MapConnection : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MapConnection object using the connection string found in the 'MapConnection' section of the application configuration file.
        /// </summary>
        public MapConnection() : 
                base("name=MapConnection", "MapConnection")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MapConnection object.
        /// </summary>
        public MapConnection(string connectionString) : 
                base(connectionString, "MapConnection")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MapConnection object.
        /// </summary>
        public MapConnection(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MapConnection")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Persona in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Persona> Persona
        {
            get
            {
                if ((this._Persona == null))
                {
                    this._Persona = base.CreateQuery<Persona>("[Persona]");
                }
                return this._Persona;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Persona> _Persona;
        /// <summary>
        /// There are no comments for Slimība in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Slimība> Slimība
        {
            get
            {
                if ((this._Slimība == null))
                {
                    this._Slimība = base.CreateQuery<Slimība>("[Slimība]");
                }
                return this._Slimība;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Slimība> _Slimība;
        /// <summary>
        /// There are no comments for Ārstēšana in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Ārstēšana> Ārstēšana
        {
            get
            {
                if ((this._Ārstēšana == null))
                {
                    this._Ārstēšana = base.CreateQuery<Ārstēšana>("[Ārstēšana]");
                }
                return this._Ārstēšana;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Ārstēšana> _Ārstēšana;
        /// <summary>
        /// There are no comments for ĀrstsPacients in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ĀrstsPacients> ĀrstsPacients
        {
            get
            {
                if ((this._ĀrstsPacients == null))
                {
                    this._ĀrstsPacients = base.CreateQuery<ĀrstsPacients>("[ĀrstsPacients]");
                }
                return this._ĀrstsPacients;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ĀrstsPacients> _ĀrstsPacients;
        /// <summary>
        /// There are no comments for PersonasValidācijaSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PersonasValidācija> PersonasValidācijaSet
        {
            get
            {
                if ((this._PersonasValidācijaSet == null))
                {
                    this._PersonasValidācijaSet = base.CreateQuery<PersonasValidācija>("[PersonasValidācijaSet]");
                }
                return this._PersonasValidācijaSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PersonasValidācija> _PersonasValidācijaSet;
        /// <summary>
        /// There are no comments for Persona in the schema.
        /// </summary>
        public void AddToPersona(Persona persona)
        {
            base.AddObject("Persona", persona);
        }
        /// <summary>
        /// There are no comments for Slimība in the schema.
        /// </summary>
        public void AddToSlimība(Slimība slimība)
        {
            base.AddObject("Slimība", slimība);
        }
        /// <summary>
        /// There are no comments for Ārstēšana in the schema.
        /// </summary>
        public void AddToĀrstēšana(Ārstēšana ārstēšana)
        {
            base.AddObject("Ārstēšana", ārstēšana);
        }
        /// <summary>
        /// There are no comments for ĀrstsPacients in the schema.
        /// </summary>
        public void AddToĀrstsPacients(ĀrstsPacients ārstsPacients)
        {
            base.AddObject("ĀrstsPacients", ārstsPacients);
        }
        /// <summary>
        /// There are no comments for PersonasValidācijaSet in the schema.
        /// </summary>
        public void AddToPersonasValidācijaSet(PersonasValidācija personasValidācija)
        {
            base.AddObject("PersonasValidācijaSet", personasValidācija);
        }
        /// <summary>
        /// There are no comments for HealthCentreModel.CheckPerson in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<PersonasValidācija> CheckPerson(string username, string password)
        {
            global::System.Data.Objects.ObjectParameter usernameParameter;
            if ((username != null))
            {
                usernameParameter = new global::System.Data.Objects.ObjectParameter("Username", username);
            }
            else
            {
                usernameParameter = new global::System.Data.Objects.ObjectParameter("Username", typeof(string));
            }
            global::System.Data.Objects.ObjectParameter passwordParameter;
            if ((password != null))
            {
                passwordParameter = new global::System.Data.Objects.ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new global::System.Data.Objects.ObjectParameter("Password", typeof(string));
            }
            return base.ExecuteFunction<PersonasValidācija>("CheckPerson", usernameParameter, passwordParameter);
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Persona in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Persona")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::HealthSystem.Business.Ārsts))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::HealthSystem.Business.Pacients))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::HealthSystem.Business.Administrators))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::HealthSystem.Business.Reģ_darb))]
    public abstract partial class Persona : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// There are no comments for Property PersonasID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonasID
        {
            get
            {
                return this._PersonasID;
            }
            set
            {
                this.OnPersonasIDChanging(value);
                this.ReportPropertyChanging("PersonasID");
                this._PersonasID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PersonasID");
                this.OnPersonasIDChanged();
            }
        }
        private int _PersonasID;
        partial void OnPersonasIDChanging(int value);
        partial void OnPersonasIDChanged();
        /// <summary>
        /// There are no comments for Property Vārds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Vārds
        {
            get
            {
                return this._Vārds;
            }
            set
            {
                this.OnVārdsChanging(value);
                this.ReportPropertyChanging("Vārds");
                this._Vārds = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Vārds");
                this.OnVārdsChanged();
            }
        }
        private string _Vārds;
        partial void OnVārdsChanging(string value);
        partial void OnVārdsChanged();
        /// <summary>
        /// There are no comments for Property Uzvārds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Uzvārds
        {
            get
            {
                return this._Uzvārds;
            }
            set
            {
                this.OnUzvārdsChanging(value);
                this.ReportPropertyChanging("Uzvārds");
                this._Uzvārds = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Uzvārds");
                this.OnUzvārdsChanged();
            }
        }
        private string _Uzvārds;
        partial void OnUzvārdsChanging(string value);
        partial void OnUzvārdsChanged();
        /// <summary>
        /// There are no comments for Property Personas_kods in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Personas_kods
        {
            get
            {
                return this._Personas_kods;
            }
            set
            {
                this.OnPersonas_kodsChanging(value);
                this.ReportPropertyChanging("Personas_kods");
                this._Personas_kods = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Personas_kods");
                this.OnPersonas_kodsChanged();
            }
        }
        private string _Personas_kods;
        partial void OnPersonas_kodsChanging(string value);
        partial void OnPersonas_kodsChanged();
        /// <summary>
        /// There are no comments for Property Telefons in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefons
        {
            get
            {
                return this._Telefons;
            }
            set
            {
                this.OnTelefonsChanging(value);
                this.ReportPropertyChanging("Telefons");
                this._Telefons = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Telefons");
                this.OnTelefonsChanged();
            }
        }
        private int _Telefons;
        partial void OnTelefonsChanging(int value);
        partial void OnTelefonsChanged();
        /// <summary>
        /// There are no comments for Property Adrese in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Adrese
        {
            get
            {
                return this._Adrese;
            }
            set
            {
                this.OnAdreseChanging(value);
                this.ReportPropertyChanging("Adrese");
                this._Adrese = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Adrese");
                this.OnAdreseChanged();
            }
        }
        private string _Adrese;
        partial void OnAdreseChanging(string value);
        partial void OnAdreseChanged();
        /// <summary>
        /// There are no comments for Property Lietotājvārds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Lietotājvārds
        {
            get
            {
                return this._Lietotājvārds;
            }
            set
            {
                this.OnLietotājvārdsChanging(value);
                this.ReportPropertyChanging("Lietotājvārds");
                this._Lietotājvārds = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Lietotājvārds");
                this.OnLietotājvārdsChanged();
            }
        }
        private string _Lietotājvārds;
        partial void OnLietotājvārdsChanging(string value);
        partial void OnLietotājvārdsChanged();
        /// <summary>
        /// There are no comments for Property Parole in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Parole
        {
            get
            {
                return this._Parole;
            }
            set
            {
                this.OnParoleChanging(value);
                this.ReportPropertyChanging("Parole");
                this._Parole = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Parole");
                this.OnParoleChanged();
            }
        }
        private string _Parole;
        partial void OnParoleChanging(string value);
        partial void OnParoleChanged();
        /// <summary>
        /// There are no comments for Property Attēls in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Attēls
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Attēls);
            }
            set
            {
                this.OnAttēlsChanging(value);
                this.ReportPropertyChanging("Attēls");
                this._Attēls = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Attēls");
                this.OnAttēlsChanged();
            }
        }
        private byte[] _Attēls;
        partial void OnAttēlsChanging(byte[] value);
        partial void OnAttēlsChanged();
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Slimība in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SlimībasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Slimība")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Slimība : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Slimība object.
        /// </summary>
        /// <param name="slimībasID">Initial value of SlimībasID.</param>
        /// <param name="diagnoze">Initial value of Diagnoze.</param>
        /// <param name="simptomi">Initial value of Simptomi.</param>
        public static Slimība CreateSlimība(int slimībasID, string diagnoze, string simptomi)
        {
            Slimība slimība = new Slimība();
            slimība.SlimībasID = slimībasID;
            slimība.Diagnoze = diagnoze;
            slimība.Simptomi = simptomi;
            return slimība;
        }
        /// <summary>
        /// There are no comments for Property SlimībasID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SlimībasID
        {
            get
            {
                return this._SlimībasID;
            }
            set
            {
                this.OnSlimībasIDChanging(value);
                this.ReportPropertyChanging("SlimībasID");
                this._SlimībasID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SlimībasID");
                this.OnSlimībasIDChanged();
            }
        }
        private int _SlimībasID;
        partial void OnSlimībasIDChanging(int value);
        partial void OnSlimībasIDChanged();
        /// <summary>
        /// There are no comments for Property Diagnoze in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnoze
        {
            get
            {
                return this._Diagnoze;
            }
            set
            {
                this.OnDiagnozeChanging(value);
                this.ReportPropertyChanging("Diagnoze");
                this._Diagnoze = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Diagnoze");
                this.OnDiagnozeChanged();
            }
        }
        private string _Diagnoze;
        partial void OnDiagnozeChanging(string value);
        partial void OnDiagnozeChanged();
        /// <summary>
        /// There are no comments for Property Simptomi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Simptomi
        {
            get
            {
                return this._Simptomi;
            }
            set
            {
                this.OnSimptomiChanging(value);
                this.ReportPropertyChanging("Simptomi");
                this._Simptomi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Simptomi");
                this.OnSimptomiChanged();
            }
        }
        private string _Simptomi;
        partial void OnSimptomiChanging(string value);
        partial void OnSimptomiChanged();
        /// <summary>
        /// There are no comments for Ārstēšana in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "FK_Ārstēšana_Slimība", "Ārstēšana")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Ārstēšana> Ārstēšana
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Ārstēšana>("HealthCentreModel.FK_Ārstēšana_Slimība", "Ārstēšana");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Ārstēšana>("HealthCentreModel.FK_Ārstēšana_Slimība", "Ārstēšana", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Administrators in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Administrators")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Administrators : Persona
    {
        /// <summary>
        /// Create a new Administrators object.
        /// </summary>
        /// <param name="personasID">Initial value of PersonasID.</param>
        /// <param name="vārds">Initial value of Vārds.</param>
        /// <param name="uzvārds">Initial value of Uzvārds.</param>
        /// <param name="personas_kods">Initial value of Personas_kods.</param>
        /// <param name="telefons">Initial value of Telefons.</param>
        /// <param name="adrese">Initial value of Adrese.</param>
        /// <param name="lietotājvārds">Initial value of Lietotājvārds.</param>
        /// <param name="parole">Initial value of Parole.</param>
        public static Administrators CreateAdministrators(int personasID, string vārds, string uzvārds, string personas_kods, int telefons, string adrese, string lietotājvārds, string parole)
        {
            Administrators administrators = new Administrators();
            administrators.PersonasID = personasID;
            administrators.Vārds = vārds;
            administrators.Uzvārds = uzvārds;
            administrators.Personas_kods = personas_kods;
            administrators.Telefons = telefons;
            administrators.Adrese = adrese;
            administrators.Lietotājvārds = lietotājvārds;
            administrators.Parole = parole;
            return administrators;
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Ārsts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Ārsts")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Ārsts : Persona
    {
        /// <summary>
        /// Create a new Ārsts object.
        /// </summary>
        /// <param name="personasID">Initial value of PersonasID.</param>
        /// <param name="vārds">Initial value of Vārds.</param>
        /// <param name="uzvārds">Initial value of Uzvārds.</param>
        /// <param name="personas_kods">Initial value of Personas_kods.</param>
        /// <param name="telefons">Initial value of Telefons.</param>
        /// <param name="adrese">Initial value of Adrese.</param>
        /// <param name="lietotājvārds">Initial value of Lietotājvārds.</param>
        /// <param name="parole">Initial value of Parole.</param>
        public static Ārsts CreateĀrsts(int personasID, string vārds, string uzvārds, string personas_kods, int telefons, string adrese, string lietotājvārds, string parole)
        {
            Ārsts ārsts = new Ārsts();
            ārsts.PersonasID = personasID;
            ārsts.Vārds = vārds;
            ārsts.Uzvārds = uzvārds;
            ārsts.Personas_kods = personas_kods;
            ārsts.Telefons = telefons;
            ārsts.Adrese = adrese;
            ārsts.Lietotājvārds = lietotājvārds;
            ārsts.Parole = parole;
            return ārsts;
        }
        /// <summary>
        /// There are no comments for Property Specializācija in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Specializācija
        {
            get
            {
                return this._Specializācija;
            }
            set
            {
                this.OnSpecializācijaChanging(value);
                this.ReportPropertyChanging("Specializācija");
                this._Specializācija = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Specializācija");
                this.OnSpecializācijaChanged();
            }
        }
        private string _Specializācija;
        partial void OnSpecializācijaChanging(string value);
        partial void OnSpecializācijaChanged();
        /// <summary>
        /// There are no comments for Property Kabineta_numurs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> Kabineta_numurs
        {
            get
            {
                return this._Kabineta_numurs;
            }
            set
            {
                this.OnKabineta_numursChanging(value);
                this.ReportPropertyChanging("Kabineta_numurs");
                this._Kabineta_numurs = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Kabineta_numurs");
                this.OnKabineta_numursChanged();
            }
        }
        private global::System.Nullable<short> _Kabineta_numurs;
        partial void OnKabineta_numursChanging(global::System.Nullable<short> value);
        partial void OnKabineta_numursChanged();
        /// <summary>
        /// There are no comments for ĀrstsPacients in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "ĀrstsĀrstsPacients", "ĀrstsPacients")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ĀrstsPacients> ĀrstsPacients
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ĀrstsPacients>("HealthCentreModel.ĀrstsĀrstsPacients", "ĀrstsPacients");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ĀrstsPacients>("HealthCentreModel.ĀrstsĀrstsPacients", "ĀrstsPacients", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Reģ_darb in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Reģ_darb")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Reģ_darb : Persona
    {
        /// <summary>
        /// Create a new Reģ_darb object.
        /// </summary>
        /// <param name="personasID">Initial value of PersonasID.</param>
        /// <param name="vārds">Initial value of Vārds.</param>
        /// <param name="uzvārds">Initial value of Uzvārds.</param>
        /// <param name="personas_kods">Initial value of Personas_kods.</param>
        /// <param name="telefons">Initial value of Telefons.</param>
        /// <param name="adrese">Initial value of Adrese.</param>
        /// <param name="lietotājvārds">Initial value of Lietotājvārds.</param>
        /// <param name="parole">Initial value of Parole.</param>
        public static Reģ_darb CreateReģ_darb(int personasID, string vārds, string uzvārds, string personas_kods, int telefons, string adrese, string lietotājvārds, string parole)
        {
            Reģ_darb reģ_darb = new Reģ_darb();
            reģ_darb.PersonasID = personasID;
            reģ_darb.Vārds = vārds;
            reģ_darb.Uzvārds = uzvārds;
            reģ_darb.Personas_kods = personas_kods;
            reģ_darb.Telefons = telefons;
            reģ_darb.Adrese = adrese;
            reģ_darb.Lietotājvārds = lietotājvārds;
            reģ_darb.Parole = parole;
            return reģ_darb;
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Pacients in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Pacients")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pacients : Persona
    {
        /// <summary>
        /// Create a new Pacients object.
        /// </summary>
        /// <param name="personasID">Initial value of PersonasID.</param>
        /// <param name="vārds">Initial value of Vārds.</param>
        /// <param name="uzvārds">Initial value of Uzvārds.</param>
        /// <param name="personas_kods">Initial value of Personas_kods.</param>
        /// <param name="telefons">Initial value of Telefons.</param>
        /// <param name="adrese">Initial value of Adrese.</param>
        /// <param name="lietotājvārds">Initial value of Lietotājvārds.</param>
        /// <param name="parole">Initial value of Parole.</param>
        public static Pacients CreatePacients(int personasID, string vārds, string uzvārds, string personas_kods, int telefons, string adrese, string lietotājvārds, string parole)
        {
            Pacients pacients = new Pacients();
            pacients.PersonasID = personasID;
            pacients.Vārds = vārds;
            pacients.Uzvārds = uzvārds;
            pacients.Personas_kods = personas_kods;
            pacients.Telefons = telefons;
            pacients.Adrese = adrese;
            pacients.Lietotājvārds = lietotājvārds;
            pacients.Parole = parole;
            return pacients;
        }
        /// <summary>
        /// There are no comments for Property Asins_grupa in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<byte> Asins_grupa
        {
            get
            {
                return this._Asins_grupa;
            }
            set
            {
                this.OnAsins_grupaChanging(value);
                this.ReportPropertyChanging("Asins_grupa");
                this._Asins_grupa = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Asins_grupa");
                this.OnAsins_grupaChanged();
            }
        }
        private global::System.Nullable<byte> _Asins_grupa;
        partial void OnAsins_grupaChanging(global::System.Nullable<byte> value);
        partial void OnAsins_grupaChanged();
        /// <summary>
        /// There are no comments for ĀrstsPacients in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "PacientsĀrstsPacients", "ĀrstsPacients")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ĀrstsPacients> ĀrstsPacients
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ĀrstsPacients>("HealthCentreModel.PacientsĀrstsPacients", "ĀrstsPacients");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ĀrstsPacients>("HealthCentreModel.PacientsĀrstsPacients", "ĀrstsPacients", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.Ārstēšana in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ĀrstēšanasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="Ārstēšana")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Ārstēšana : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Ārstēšana object.
        /// </summary>
        /// <param name="ārstēšanasID">Initial value of ĀrstēšanasID.</param>
        /// <param name="terapijas_kurss">Initial value of Terapijas_kurss.</param>
        /// <param name="diagnozes_datums">Initial value of Diagnozes_datums.</param>
        /// <param name="slimības_stāvoklis">Initial value of Slimības_stāvoklis.</param>
        public static Ārstēšana CreateĀrstēšana(int ārstēšanasID, string terapijas_kurss, global::System.DateTime diagnozes_datums, string slimības_stāvoklis)
        {
            Ārstēšana ārstēšana = new Ārstēšana();
            ārstēšana.ĀrstēšanasID = ārstēšanasID;
            ārstēšana.Terapijas_kurss = terapijas_kurss;
            ārstēšana.Diagnozes_datums = diagnozes_datums;
            ārstēšana.Slimības_stāvoklis = slimības_stāvoklis;
            return ārstēšana;
        }
        /// <summary>
        /// There are no comments for Property ĀrstēšanasID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ĀrstēšanasID
        {
            get
            {
                return this._ĀrstēšanasID;
            }
            set
            {
                this.OnĀrstēšanasIDChanging(value);
                this.ReportPropertyChanging("ĀrstēšanasID");
                this._ĀrstēšanasID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ĀrstēšanasID");
                this.OnĀrstēšanasIDChanged();
            }
        }
        private int _ĀrstēšanasID;
        partial void OnĀrstēšanasIDChanging(int value);
        partial void OnĀrstēšanasIDChanged();
        /// <summary>
        /// There are no comments for Property Terapijas_kurss in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Terapijas_kurss
        {
            get
            {
                return this._Terapijas_kurss;
            }
            set
            {
                this.OnTerapijas_kurssChanging(value);
                this.ReportPropertyChanging("Terapijas_kurss");
                this._Terapijas_kurss = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Terapijas_kurss");
                this.OnTerapijas_kurssChanged();
            }
        }
        private string _Terapijas_kurss;
        partial void OnTerapijas_kurssChanging(string value);
        partial void OnTerapijas_kurssChanged();
        /// <summary>
        /// There are no comments for Property Diagnozes_datums in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Diagnozes_datums
        {
            get
            {
                return this._Diagnozes_datums;
            }
            set
            {
                this.OnDiagnozes_datumsChanging(value);
                this.ReportPropertyChanging("Diagnozes_datums");
                this._Diagnozes_datums = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Diagnozes_datums");
                this.OnDiagnozes_datumsChanged();
            }
        }
        private global::System.DateTime _Diagnozes_datums;
        partial void OnDiagnozes_datumsChanging(global::System.DateTime value);
        partial void OnDiagnozes_datumsChanged();
        /// <summary>
        /// There are no comments for Property Atveselošanas_datums in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Atveselošanas_datums
        {
            get
            {
                return this._Atveselošanas_datums;
            }
            set
            {
                this.OnAtveselošanas_datumsChanging(value);
                this.ReportPropertyChanging("Atveselošanas_datums");
                this._Atveselošanas_datums = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Atveselošanas_datums");
                this.OnAtveselošanas_datumsChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Atveselošanas_datums;
        partial void OnAtveselošanas_datumsChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAtveselošanas_datumsChanged();
        /// <summary>
        /// There are no comments for Property Slimības_stāvoklis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Slimības_stāvoklis
        {
            get
            {
                return this._Slimības_stāvoklis;
            }
            set
            {
                this.OnSlimības_stāvoklisChanging(value);
                this.ReportPropertyChanging("Slimības_stāvoklis");
                this._Slimības_stāvoklis = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Slimības_stāvoklis");
                this.OnSlimības_stāvoklisChanged();
            }
        }
        private string _Slimības_stāvoklis;
        partial void OnSlimības_stāvoklisChanging(string value);
        partial void OnSlimības_stāvoklisChanged();
        /// <summary>
        /// There are no comments for Slimība in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "FK_Ārstēšana_Slimība", "Slimība")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Slimība Slimība
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Slimība>("HealthCentreModel.FK_Ārstēšana_Slimība", "Slimība").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Slimība>("HealthCentreModel.FK_Ārstēšana_Slimība", "Slimība").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Slimība in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Slimība> SlimībaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Slimība>("HealthCentreModel.FK_Ārstēšana_Slimība", "Slimība");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Slimība>("HealthCentreModel.FK_Ārstēšana_Slimība", "Slimība", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ĀrstsPacients in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "FK_Ārstēšana_ĀrstsPersona", "ĀrstsPacients")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ĀrstsPacients ĀrstsPacients
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ĀrstsPacients>("HealthCentreModel.FK_Ārstēšana_ĀrstsPersona", "ĀrstsPacients").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ĀrstsPacients>("HealthCentreModel.FK_Ārstēšana_ĀrstsPersona", "ĀrstsPacients").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ĀrstsPacients in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ĀrstsPacients> ĀrstsPacientsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ĀrstsPacients>("HealthCentreModel.FK_Ārstēšana_ĀrstsPersona", "ĀrstsPacients");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ĀrstsPacients>("HealthCentreModel.FK_Ārstēšana_ĀrstsPersona", "ĀrstsPacients", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.ĀrstsPacients in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ĀrstaPacientaID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="ĀrstsPacients")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ĀrstsPacients : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ĀrstsPacients object.
        /// </summary>
        /// <param name="ārstaPacientaID">Initial value of ĀrstaPacientaID.</param>
        public static ĀrstsPacients CreateĀrstsPacients(int ārstaPacientaID)
        {
            ĀrstsPacients ārstsPacients = new ĀrstsPacients();
            ārstsPacients.ĀrstaPacientaID = ārstaPacientaID;
            return ārstsPacients;
        }
        /// <summary>
        /// There are no comments for Property ĀrstaPacientaID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ĀrstaPacientaID
        {
            get
            {
                return this._ĀrstaPacientaID;
            }
            set
            {
                this.OnĀrstaPacientaIDChanging(value);
                this.ReportPropertyChanging("ĀrstaPacientaID");
                this._ĀrstaPacientaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ĀrstaPacientaID");
                this.OnĀrstaPacientaIDChanged();
            }
        }
        private int _ĀrstaPacientaID;
        partial void OnĀrstaPacientaIDChanging(int value);
        partial void OnĀrstaPacientaIDChanged();
        /// <summary>
        /// There are no comments for Ārstēšana in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "FK_Ārstēšana_ĀrstsPersona", "Ārstēšana")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Ārstēšana> Ārstēšana
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Ārstēšana>("HealthCentreModel.FK_Ārstēšana_ĀrstsPersona", "Ārstēšana");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Ārstēšana>("HealthCentreModel.FK_Ārstēšana_ĀrstsPersona", "Ārstēšana", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Ārsts in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "ĀrstsĀrstsPacients", "Ārsts")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Ārsts Ārsts
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Ārsts>("HealthCentreModel.ĀrstsĀrstsPacients", "Ārsts").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Ārsts>("HealthCentreModel.ĀrstsĀrstsPacients", "Ārsts").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Ārsts in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Ārsts> ĀrstsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Ārsts>("HealthCentreModel.ĀrstsĀrstsPacients", "Ārsts");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Ārsts>("HealthCentreModel.ĀrstsĀrstsPacients", "Ārsts", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Pacients in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HealthCentreModel", "PacientsĀrstsPacients", "Pacients")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Pacients Pacients
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Pacients>("HealthCentreModel.PacientsĀrstsPacients", "Pacients").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Pacients>("HealthCentreModel.PacientsĀrstsPacients", "Pacients").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Pacients in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Pacients> PacientsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Pacients>("HealthCentreModel.PacientsĀrstsPacients", "Pacients");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Pacients>("HealthCentreModel.PacientsĀrstsPacients", "Pacients", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HealthCentreModel.PersonasValidācija in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonasID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HealthCentreModel", Name="PersonasValidācija")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PersonasValidācija : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PersonasValidācija object.
        /// </summary>
        /// <param name="personasID">Initial value of PersonasID.</param>
        /// <param name="personas_tips">Initial value of Personas_tips.</param>
        public static PersonasValidācija CreatePersonasValidācija(int personasID, byte personas_tips)
        {
            PersonasValidācija personasValidācija = new PersonasValidācija();
            personasValidācija.PersonasID = personasID;
            personasValidācija.Personas_tips = personas_tips;
            return personasValidācija;
        }
        /// <summary>
        /// There are no comments for Property PersonasID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonasID
        {
            get
            {
                return this._PersonasID;
            }
            set
            {
                this.OnPersonasIDChanging(value);
                this.ReportPropertyChanging("PersonasID");
                this._PersonasID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PersonasID");
                this.OnPersonasIDChanged();
            }
        }
        private int _PersonasID;
        partial void OnPersonasIDChanging(int value);
        partial void OnPersonasIDChanged();
        /// <summary>
        /// There are no comments for Property Personas_tips in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte Personas_tips
        {
            get
            {
                return this._Personas_tips;
            }
            set
            {
                this.OnPersonas_tipsChanging(value);
                this.ReportPropertyChanging("Personas_tips");
                this._Personas_tips = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Personas_tips");
                this.OnPersonas_tipsChanged();
            }
        }
        private byte _Personas_tips;
        partial void OnPersonas_tipsChanging(byte value);
        partial void OnPersonas_tipsChanged();
    }
}
