<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Repository">
  <eClassifiers xsi:type="ecore:EClass" name="Pasutijums">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pasutijumaId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numurs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="akceptesanasDatums" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pasutisanasDatums" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="darbiniekaId" lowerBound="1"
        eType="#//Darbinieks" eKeys="#//Darbinieks/darbiniekaId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sanemsanasDatums" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrecesVieniba">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precesVienibasId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daudzums" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pasutijumaId" lowerBound="1"
        eType="#//Pasutijums" eKeys="#//Pasutijums/pasutijumaId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precesId" lowerBound="1"
        eType="#//Prece" eKeys="#//Prece/precesId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prece">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nosaukums" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vienibasCena" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kategorija" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precesId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Darbinieks">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="darbiniekaId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uzvards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodala" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="irVaditajs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vaditajaId" eType="#//Darbinieks"
        eKeys="#//Darbinieks/darbiniekaId"/>
  </eClassifiers>
</ecore:EPackage>
