PutString Macro String
          Push Ax Dx
         
          Lea  Dx, String
          Mov  Ah, 9
          Int  21h

          Pop  Dx Ax 
          EndM
;*****************************************
MultiChar Macro Char, Counter
          Local NextChar
 
          Push  Ax Cx Dx

          Mov   Ah, 2
          Mov   Dl, Char
          Mov   Cx, Counter
NextChar:
          Int 21h
          Loop NextChar
          
          Pop Dx Cx Ax
          EndM